package co.ke.bremac.posapp;

import android.app.ProgressDialog;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.*;
import android.text.*;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.widget.*;

import androidx.appcompat.app.*;
import androidx.core.view.WindowCompat;

import co.ke.bremac.posapp.api.*;
import co.ke.bremac.posapp.auth.TokenStore;
import co.ke.bremac.posapp.cart.Cart;
import co.ke.bremac.posapp.util.Money;

import org.json.*;

import java.net.URISyntaxException;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends AppCompatActivity implements ApiClient.TokenProvider {
    private static final int DARK=Color.rgb(16,47,43), DARK2=Color.rgb(19,62,56), ACCENT=Color.rgb(17,166,131), GREEN=Color.rgb(19,115,91), CANVAS=Color.rgb(247,249,247), INK=Color.rgb(24,39,35), MUTED=Color.rgb(101,117,111), BAD=Color.rgb(176,52,52);
    private final ExecutorService io=Executors.newSingleThreadExecutor(); private final Handler main=new Handler(Looper.getMainLooper()); private final Cart cart=new Cart();
    private LinearLayout root,content,actions; private ProgressBar loading; private SharedPreferences prefs; private TokenStore tokenStore; private PosApi api;
    private String serverUrl="", locationId="", period="today", saleStatus="final", screen="login"; private Money money=Money.kes();
    private JSONObject business,user,permissions,register,selectedCustomer; private JSONArray locations=new JSONArray(), paymentMethods=new JSONArray(); private Runnable productSearch;

    @Override public void onCreate(Bundle b){super.onCreate(b); WindowCompat.setDecorFitsSystemWindows(getWindow(),true); getWindow().setStatusBarColor(DARK); getWindow().setNavigationBarColor(DARK); prefs=getSharedPreferences("pos_app",MODE_PRIVATE); tokenStore=new TokenStore(this); serverUrl=prefs.getString("server_url",""); locationId=prefs.getString("location_id",""); shell(); if(!serverUrl.isEmpty()&&!token().isEmpty()) initApi(); if(api==null) login(""); else loadMe("",true);}
    @Override public String token(){return tokenStore.get();}
    @Override public void onUnauthenticated(){main.post(()->{tokenStore.clear(); cart.clear(); login("Your session has expired. Please sign in again.");});}
    private void initApi(){api=new PosApi(new ApiClient(serverUrl,this));}

    private void shell(){root=new LinearLayout(this); root.setOrientation(LinearLayout.VERTICAL); root.setBackgroundColor(CANVAS); setContentView(root);
        LinearLayout bar=row(); bar.setPadding(dp(16),dp(10),dp(12),dp(10)); bar.setBackgroundColor(DARK); root.addView(bar,new LinearLayout.LayoutParams(-1,dp(64)));
        TextView mark=tv("B",18,Color.WHITE,Typeface.BOLD); mark.setGravity(Gravity.CENTER); mark.setBackground(bg(ACCENT,12)); bar.addView(mark,new LinearLayout.LayoutParams(dp(40),dp(40)));
        TextView title=tv("BreMac POS",18,Color.WHITE,Typeface.BOLD); title.setPadding(dp(12),0,0,0); bar.addView(title,new LinearLayout.LayoutParams(0,-2,1)); actions=row(); bar.addView(actions);
        loading=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal); loading.setIndeterminate(true); loading.setVisibility(View.GONE); root.addView(loading,new LinearLayout.LayoutParams(-1,dp(3)));
        ScrollView sv=new ScrollView(this); sv.setFillViewport(true); root.addView(sv,new LinearLayout.LayoutParams(-1,0,1)); content=new LinearLayout(this); content.setOrientation(LinearLayout.VERTICAL); content.setPadding(dp(16),dp(16),dp(16),dp(24)); sv.addView(content,new ScrollView.LayoutParams(-1,-2));}
    private void clear(String s){screen=s; content.removeAllViews(); actions.removeAllViews();}
    private void nav(){actions.removeAllViews(); Button h=tiny("Home"),p=tiny("POS"),s=tiny("Sales"),o=tiny("Out"); h.setOnClickListener(v->home("")); p.setOnClickListener(v->pos()); s.setOnClickListener(v->sales()); o.setOnClickListener(v->signOut()); actions.addView(h);actions.addView(p);actions.addView(s);actions.addView(o);}

    private void login(String msg){clear("login"); h1("Sign in"); para("Native Android client for the BreMac POS Mobile API v1. HTTPS is required."); if(!msg.isEmpty()) alert(msg);
        EditText server=input("https://pos.example.com",InputType.TYPE_TEXT_VARIATION_URI); server.setText(serverUrl); add(server,54,8);
        EditText name=input("Username",InputType.TYPE_CLASS_TEXT), pass=input("Password",InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD); add(name,54,8); add(pass,54,8);
        Button b=primary("Sign in"); add(b,52,12); b.setOnClickListener(v->{try{serverUrl=ServerUrl.normalize(server.getText().toString()); prefs.edit().putString("server_url",serverUrl).apply(); initApi(); run("Signing in",()->api.login(name.getText().toString(),pass.getText().toString(),device(),null),e->auth(e.optJSONObject("data")));}catch(IllegalArgumentException|URISyntaxException e){alert(e.getMessage());}});}
    private void auth(JSONObject d)throws Exception{ if(d==null)return; if("otp_required".equals(d.optString("status"))) otp(d,""); else {tokenStore.save(d.optString("token")); loadMe("",true);} }
    private void otp(JSONObject d,String msg){clear("otp"); h1("OTP verification"); para("Enter the 6-digit code sent to "+d.optString("delivery_target")+"."); if(!msg.isEmpty())alert(msg); EditText code=input("123456",InputType.TYPE_CLASS_NUMBER); code.setFilters(new InputFilter[]{new InputFilter.LengthFilter(6)}); add(code,54,8); Button verify=primary("Verify"); add(verify,52,8);
        LinearLayout r=row(); Button sms=secondary("Resend SMS"), email=secondary("Resend email"); r.addView(sms,new LinearLayout.LayoutParams(0,dp(48),1)); r.addView(email,new LinearLayout.LayoutParams(0,dp(48),1)); content.addView(r,lp(-1,-2,8));
        verify.setOnClickListener(v->run("Verifying",()->api.verifyOtp(d.optString("otp_session"),code.getText().toString(),device()),e->{try{auth(e.optJSONObject("data"));}catch(Exception ex){throw new RuntimeException(ex);}}));
        View.OnClickListener resend=v->run("Resending",()->api.resendOtp(d.optString("otp_session"),v==email?"email":"sms"),e->{JSONObject nd=e.optJSONObject("data"); nd.put("otp_session",d.optString("otp_session")); otp(nd,"Code resent.");}); sms.setOnClickListener(resend); email.setOnClickListener(resend);}

    private void loadMe(String msg,boolean dash){run("Loading",()->api.me(),e->{JSONObject me=e.optJSONObject("data"); user=me.optJSONObject("user"); business=me.optJSONObject("business"); locations=me.optJSONArray("locations")==null?new JSONArray():me.optJSONArray("locations"); permissions=me.optJSONObject("permissions"); register=me.optJSONObject("register"); JSONObject c=business==null?null:business.optJSONObject("currency"); if(c!=null)money=new Money(c.optString("code"),c.optString("symbol"),c.optString("thousand_separator",","),c.optString("decimal_separator","."),c.optInt("precision",2)); if(locationId.isEmpty()&&locations.length()>0)locationId=String.valueOf(locations.optJSONObject(0).optInt("id")); prefs.edit().putString("location_id",locationId).apply(); if(dash)home(msg); else nav();});}
    private void home(String msg){clear("home"); nav(); if(!msg.isEmpty())alert(msg); h1(business==null?"Dashboard":business.optString("name","Dashboard")); para((user==null?"":user.optString("full_name",user.optString("username")))+" • "+device()); loc(()->home("")); chips(); registerBanner(); Button refresh=secondary("Refresh"); add(refresh,48,8); refresh.setOnClickListener(v->home(""));
        run("Dashboard",()->api.dashboard(locationId,period),e->{if(!screen.equals("home"))return; JSONObject d=e.optJSONObject("data"); if(d==null)return; String[][] cs={{"Total sales","total_sales"},{"Sales count","sales_count"},{"Paid","total_paid"},{"Due","total_due"},{"Expenses","total_expense"},{"Net","net"}}; for(String[] c:cs) card(c[0],c[1].equals("sales_count")?""+d.optInt(c[1]):money.format(d.optDouble(c[1]))); h2("Recent sales"); JSONArray a=d.optJSONArray("recent_sales"); if(a==null||a.length()==0)para("No recent sales."); else for(int i=0;i<a.length();i++) saleRow(content,a.optJSONObject(i));});}
    private void chips(){LinearLayout r=row(); for(String x:new String[]{"today","week","month"}){Button b=x.equals(period)?primary(cap(x)):secondary(cap(x)); b.setOnClickListener(v->{period=x;home("");}); r.addView(b,new LinearLayout.LayoutParams(0,dp(48),1));} content.addView(r,lp(-1,-2,8));}
    private void registerBanner(){boolean open=register!=null&&"open".equals(register.optString("status")); TextView t=tv(open?"Register open":"Register closed",15,open?GREEN:BAD,Typeface.BOLD); t.setPadding(dp(12),dp(10),dp(12),dp(10)); t.setBackground(bg(open?Color.rgb(229,247,239):Color.rgb(255,238,235),10)); content.addView(t,lp(-1,-2,8)); Button b=open?secondary("Close register"):primary("Open register"); add(b,48,6); b.setOnClickListener(v->{if(open) closeRegister(); else openRegister(()->loadMe("Register opened.",true));});}

    private void pos(){clear("pos"); nav(); h1("New sale"); loc(this::pos); loadPayments(); EditText barcode=input("Scan barcode/SKU then Enter",InputType.TYPE_CLASS_TEXT); add(barcode,54,6); barcode.setOnEditorActionListener((v,a,e)->{if(a==EditorInfo.IME_ACTION_DONE||(e!=null&&e.getKeyCode()==KeyEvent.KEYCODE_ENTER)){lookup(barcode.getText().toString()); barcode.setText(""); return true;} return false;});
        EditText search=input("Search products",InputType.TYPE_CLASS_TEXT); add(search,54,6); LinearLayout results=col(); content.addView(results); search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){} public void afterTextChanged(Editable e){} public void onTextChanged(CharSequence s,int a,int b,int c){if(productSearch!=null)main.removeCallbacks(productSearch); productSearch=()->searchProducts(s.toString(),results); main.postDelayed(productSearch,350);}});
        Button cust=secondary("Customer: Walk-in / choose"); cust.setOnClickListener(v->customers(cust)); add(cust,48,8); h2("Cart"); cartUi();}
    private void searchProducts(String q,LinearLayout results){if(q.trim().isEmpty()){results.removeAllViews();return;} run("",()->api.products(q,locationId,1),e->{results.removeAllViews(); JSONArray a=e.optJSONArray("data"); if(a==null||a.length()==0){results.addView(tv("No products found.",14,MUTED,0));return;} for(int i=0;i<a.length();i++) productRow(results,a.optJSONObject(i));});}
    private void lookup(String code){if(code.trim().isEmpty())return; run("Lookup",()->api.lookup(code,locationId),e->addProduct(e.optJSONObject("data")));}
    private void productRow(LinearLayout parent,JSONObject p){boolean out=p.optBoolean("enable_stock")&&p.optDouble("stock")<=0; Button b=secondary(p.optString("name")+"\n"+p.optString("sku")+" • "+money.format(p.optDouble("price_inc_tax"))+" • Stock: "+(p.isNull("stock")?"n/a":p.optString("stock"))+(out?" (out)":"")); b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL); b.setEnabled(!out); b.setOnClickListener(v->addProduct(p)); parent.addView(b,lp(-1,64,6));}
    private void addProduct(JSONObject p){if(p==null)return; if(p.optBoolean("enable_stock")&&p.optDouble("stock")<=0){toast("Out of stock.");return;} cart.add(p.optInt("variation_id"),p.optString("name"),p.optString("sku"),p.optDouble("price_inc_tax")); pos();}
    private void cartUi(){if(cart.lines.isEmpty()){para("Cart is empty.");return;} for(Cart.Line l:new ArrayList<>(cart.lines)){LinearLayout c=cardBox(); c.addView(tv(l.name+"\n"+l.sku,15,INK,Typeface.BOLD)); LinearLayout r=row(); Button m=secondary("−"), p=secondary("+"), rm=secondary("Remove"); TextView q=tv(""+l.quantity,16,INK,Typeface.BOLD); q.setGravity(Gravity.CENTER); r.addView(m,new LinearLayout.LayoutParams(dp(48),dp(48))); r.addView(q,new LinearLayout.LayoutParams(0,dp(48),1)); r.addView(p,new LinearLayout.LayoutParams(dp(48),dp(48))); r.addView(rm,new LinearLayout.LayoutParams(dp(96),dp(48))); c.addView(r); if(permissions!=null&&permissions.optBoolean("edit_price")){EditText price=input("Unit price",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL); price.setText(""+l.unitPrice); price.setOnFocusChangeListener((v,h)->{if(!h){l.unitPrice=num(price);pos();}}); c.addView(price,lp(-1,54,6));} c.addView(tv("Line: "+money.format(l.quantity*l.unitPrice),14,GREEN,Typeface.BOLD)); content.addView(c,lp(-1,-2,8)); m.setOnClickListener(v->{l.quantity--; if(l.quantity<=0)cart.remove(l.variationId); pos();}); p.setOnClickListener(v->{l.quantity++; pos();}); rm.setOnClickListener(v->{cart.remove(l.variationId);pos();});} discountUi(); totals(); Button co=primary("Checkout"); co.setOnClickListener(v->checkout()); add(co,52,10);}
    private void discountUi(){if(permissions==null||!permissions.optBoolean("discount"))return; LinearLayout r=row(); Button f=cart.discountType.equals("fixed")?primary("Fixed"):secondary("Fixed"), pct=cart.discountType.equals("percentage")?primary("%"):secondary("%"); EditText a=input("Discount",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL); a.setText(""+cart.discountAmount); r.addView(f,new LinearLayout.LayoutParams(dp(90),dp(52))); r.addView(pct,new LinearLayout.LayoutParams(dp(70),dp(52))); r.addView(a,new LinearLayout.LayoutParams(0,dp(52),1)); content.addView(r,lp(-1,-2,8)); f.setOnClickListener(v->{cart.discountType="fixed";cart.discountAmount=num(a);pos();}); pct.setOnClickListener(v->{cart.discountType="percentage";cart.discountAmount=num(a);pos();}); a.setOnFocusChangeListener((v,h)->{if(!h){cart.discountAmount=num(a);pos();}});}
    private void totals(){card("Subtotal",money.format(cart.subtotal(money.precision))); card("Discount",money.format(cart.discount(money.precision))); card("Total",money.format(cart.total(money.precision)));}

    private void checkout(){clear("checkout"); nav(); h1("Checkout"); totals(); h2("Payments"); if(cart.payments.isEmpty())para("No payments added."); else for(Cart.Payment p:cart.payments)card(p.label==null?p.method:p.label,money.format(p.amount)); card("Paid",money.format(cart.paid(money.precision))); card("Balance",money.format(cart.balance(money.precision))); card("Change",money.format(cart.change(money.precision))); Button pay=primary("Add payment"), fin=primary("Complete sale"), draft=secondary("Save draft"), quote=secondary("Save quotation"); add(pay,52,8); add(fin,52,8); add(draft,48,6); add(quote,48,6); pay.setOnClickListener(v->payment()); fin.setOnClickListener(v->{if(cart.balance(money.precision)>0)alert("Final sales require full payment."); else submit("final");}); draft.setOnClickListener(v->submit("draft")); quote.setOnClickListener(v->submit("quotation"));}
    private void payment(){LinearLayout box=col(); Spinner sp=new Spinner(this); ArrayList<String> labels=new ArrayList<>(); for(int i=0;i<paymentMethods.length();i++){JSONObject m=paymentMethods.optJSONObject(i); labels.add(m.optString("label",m.optString("key")));} if(labels.isEmpty())labels.add("Cash"); sp.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,labels)); box.addView(sp); EditText amount=input("Amount",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL); amount.setText(""+cart.balance(money.precision)); EditText phone=input("M-Pesa phone",InputType.TYPE_CLASS_PHONE), card=input("Card last digits",InputType.TYPE_CLASS_TEXT), trx=input("Transaction/reference",InputType.TYPE_CLASS_TEXT); box.addView(amount);box.addView(phone);box.addView(card);box.addView(trx); new AlertDialog.Builder(this).setTitle("Add payment").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Add",(d,w)->{JSONObject m=paymentMethods.optJSONObject(sp.getSelectedItemPosition()); String key=m==null?"cash":m.optString("key","cash"), lab=m==null?labels.get(0):m.optString("label",key); if("mpesa".equalsIgnoreCase(key))mpesa(phone.getText().toString(),num(amount),lab); else{Cart.Payment p=new Cart.Payment();p.method=key;p.label=lab;p.amount=num(amount);p.cardNumber=card.getText().toString();p.transactionNo=trx.getText().toString();cart.payments.add(p);checkout();}}).show();}
    private void mpesa(String phone,double amount,String label){ProgressDialog d=new ProgressDialog(this); d.setTitle("M-Pesa STK Push"); d.setMessage("Waiting for confirmation..."); d.setCancelable(true); d.show(); final boolean[] cancel={false}; d.setOnCancelListener(x->cancel[0]=true); run("",()->api.stk(phone,amount,locationId),e->pollMpesa(d,e.optJSONObject("data").optString("checkout_request_id"),phone,amount,label,System.currentTimeMillis(),cancel));}
    private void pollMpesa(ProgressDialog d,String id,String phone,double amount,String label,long start,boolean[] cancel){if(cancel[0]||System.currentTimeMillis()-start>90000){d.dismiss();toast("M-Pesa confirmation timed out.");return;} main.postDelayed(()->run("",()->api.mpesaStatus(id),e->{JSONObject x=e.optJSONObject("data"); String s=x.optString("status"); if("paid".equals(s)){d.dismiss(); Cart.Payment p=new Cart.Payment(); p.method="mpesa";p.label=label;p.amount=amount;p.checkoutRequestId=id;p.mpesaPhone=phone;p.transactionNo=x.optString("receipt_number");cart.payments.add(p);checkout();} else if("failed".equals(s)||"cancelled".equals(s)){d.dismiss();alert(x.optString("message","M-Pesa payment was not completed."));} else pollMpesa(d,id,phone,amount,label,start,cancel);}),3000);}
    private void submit(String status){try{JSONObject b=new JSONObject().put("location_id",Integer.parseInt(locationId)).put("contact_id",selectedCustomer==null||selectedCustomer.optBoolean("is_default")?JSONObject.NULL:selectedCustomer.optInt("id")).put("status",status).put("discount_type",cart.discountType).put("discount_amount",cart.discountAmount).put("note","").put("change_return",cart.change(money.precision)).put("client_reference",cart.clientReference); JSONArray items=new JSONArray(); for(Cart.Line l:cart.lines)items.put(new JSONObject().put("variation_id",l.variationId).put("quantity",l.quantity).put("unit_price_inc_tax",l.unitPrice).put("note","")); b.put("items",items); JSONArray pays=new JSONArray(); for(Cart.Payment p:cart.payments)pays.put(new JSONObject().put("method",p.method).put("amount",p.amount).put("note",p.note).put("card_number",p.cardNumber).put("transaction_no",p.transactionNo).put("checkout_request_id",p.checkoutRequestId).put("mpesa_phone",p.mpesaPhone)); b.put("payments",pays); run("Saving",()->api.createSale(b),e->{JSONObject sale=e.optJSONObject("data"); cart.clear(); receipt(sale);});}catch(Exception e){alert(e.getMessage());}}
    private void receipt(JSONObject s){clear("receipt"); nav(); h1("Sale saved"); TextView r=tv(s==null?"Sale completed.":s.optString("receipt_text","No receipt text returned."),14,INK,Typeface.NORMAL); r.setTypeface(Typeface.MONOSPACE); r.setPadding(dp(12),dp(12),dp(12),dp(12)); r.setBackground(bg(Color.WHITE,10)); content.addView(r,lp(-1,-2,8)); Button sh=primary("Share"), inv=secondary("Open invoice"), nw=secondary("New sale"); add(sh,48,8);add(inv,48,6);add(nw,48,6); sh.setOnClickListener(v->share(s.optString("receipt_text"))); inv.setOnClickListener(v->openHttps(s.optString("receipt_url"))); nw.setOnClickListener(v->pos());}

    private void sales(){clear("sales"); nav(); h1("Sales history"); loc(this::sales); LinearLayout tabs=row(); for(String x:new String[]{"final","draft","quotation"}){Button b=x.equals(saleStatus)?primary(cap(x)):secondary(cap(x)); b.setOnClickListener(v->{saleStatus=x;sales();}); tabs.addView(b,new LinearLayout.LayoutParams(0,dp(48),1));} content.addView(tabs,lp(-1,-2,8)); EditText q=input("Search invoice/customer",InputType.TYPE_CLASS_TEXT); add(q,54,6); Button go=secondary("Search"); add(go,48,6); LinearLayout list=col(); content.addView(list); final int[] page={1}, last={1}; Runnable[] load=new Runnable[1]; load[0]=()->run("Sales",()->api.sales(saleStatus,locationId,q.getText().toString(),page[0]),e->{JSONObject m=e.optJSONObject("meta"); if(m!=null)last[0]=m.optInt("last_page",page[0]); JSONArray a=e.optJSONArray("data"); if((a==null||a.length()==0)&&page[0]==1)para("No sales found."); else if(a!=null)for(int i=0;i<a.length();i++)saleRow(list,a.optJSONObject(i)); page[0]++;}); Button more=secondary("Load more"); add(more,48,8); go.setOnClickListener(v->{list.removeAllViews();page[0]=1;load[0].run();}); more.setOnClickListener(v->{if(page[0]<=last[0])load[0].run();}); load[0].run();}
    private void saleRow(LinearLayout parent,JSONObject s){Button b=secondary(s.optString("invoice_no")+" • "+s.optString("customer_name")+"\n"+money.format(s.optDouble("final_total"))+" • "+s.optString("payment_status")+" • "+s.optString("transaction_date")); b.setGravity(Gravity.LEFT|Gravity.CENTER_VERTICAL); b.setOnClickListener(v->run("Sale",()->api.sale(s.optInt("id")),e->saleDetail(e.optJSONObject("data")))); parent.addView(b,lp(-1,64,6));}
    private void saleDetail(JSONObject s){clear("sale"); nav(); h1(s.optString("invoice_no","Sale detail")); card("Customer",s.optString("customer_name")); card("Total",money.format(s.optDouble("final_total"))); h2("Items"); JSONArray items=s.optJSONArray("items"); if(items!=null)for(int i=0;i<items.length();i++){JSONObject it=items.optJSONObject(i);card(it.optString("name"),it.optDouble("quantity")+" "+it.optString("unit")+" × "+money.format(it.optDouble("unit_price_inc_tax"))+" = "+money.format(it.optDouble("line_total")));} h2("Payments"); JSONArray pays=s.optJSONArray("payments"); if(pays!=null)for(int i=0;i<pays.length();i++){JSONObject p=pays.optJSONObject(i);card(p.optString("method"),money.format(p.optDouble("amount"))+" "+p.optString("reference"));} Button sh=primary("Share receipt"); add(sh,48,8); sh.setOnClickListener(v->share(s.optString("receipt_text")));}

    private void customers(Button target){LinearLayout box=col(); EditText q=input("Search customer",InputType.TYPE_CLASS_TEXT); LinearLayout list=col(); Button add=secondary("Add customer"); box.addView(q);box.addView(add);box.addView(list); AlertDialog dlg=new AlertDialog.Builder(this).setTitle("Customer").setView(box).setNegativeButton("Close",null).create(); Runnable search=()->run("",()->api.customers(q.getText().toString(),1),e->{list.removeAllViews(); JSONArray a=e.optJSONArray("data"); if(a!=null)for(int i=0;i<a.length();i++){JSONObject c=a.optJSONObject(i); Button b=secondary(c.optString("name")+" "+c.optString("mobile")); b.setOnClickListener(v->{selectedCustomer=c;target.setText("Customer: "+c.optString("name"));dlg.dismiss();}); list.addView(b,lp(-1,48,6));}}); q.setOnEditorActionListener((v,a,e)->{search.run();return true;}); add.setOnClickListener(v->addCustomer(target,dlg)); dlg.setOnShowListener(x->search.run()); dlg.show();}
    private void addCustomer(Button target,AlertDialog parent){LinearLayout box=col(); EditText n=input("Name",1),m=input("Mobile",InputType.TYPE_CLASS_PHONE),em=input("Email",InputType.TYPE_TEXT_VARIATION_EMAIL_ADDRESS); box.addView(n);box.addView(m);box.addView(em); new AlertDialog.Builder(this).setTitle("Add customer").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->run("Customer",()->api.createCustomer(n.getText().toString(),m.getText().toString(),em.getText().toString()),e->{selectedCustomer=e.optJSONObject("data");target.setText("Customer: "+selectedCustomer.optString("name"));parent.dismiss();})).show();}
    private void loadPayments(){run("",()->api.paymentMethods(locationId),e->paymentMethods=e.optJSONArray("data")==null?new JSONArray():e.optJSONArray("data"));}
    private void loc(Runnable changed){if(locations.length()==0)return; Spinner sp=new Spinner(this); ArrayList<String> names=new ArrayList<>(); int sel=0; for(int i=0;i<locations.length();i++){JSONObject l=locations.optJSONObject(i); names.add(l.optString("name")); if(String.valueOf(l.optInt("id")).equals(locationId))sel=i;} sp.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,names)); sp.setSelection(sel); sp.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener(){boolean first=true; public void onItemSelected(AdapterView<?> p,View v,int pos,long id){if(first){first=false;return;} locationId=String.valueOf(locations.optJSONObject(pos).optInt("id")); prefs.edit().putString("location_id",locationId).apply(); changed.run();} public void onNothingSelected(AdapterView<?> p){}}); add(sp,48,8);}
    private void openRegister(Runnable after){EditText a=input("Opening amount",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL); new AlertDialog.Builder(this).setTitle("Open register").setView(a).setNegativeButton("Cancel",null).setPositiveButton("Open",(d,w)->run("Opening",()->api.openRegister(locationId,num(a)),e->{register=e.optJSONObject("data");after.run();})).show();}
    private void closeRegister(){LinearLayout box=col(); EditText a=input("Closing amount",InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL), n=input("Note",1); box.addView(a);box.addView(n); new AlertDialog.Builder(this).setTitle("Close register").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Close",(d,w)->run("Closing",()->api.closeRegister(num(a),n.getText().toString()),e->loadMe("Register closed.",true))).show();}
    private void signOut(){run("Signing out",()->{try{return api.logout();}catch(Exception e){return new JSONObject().put("success",true);}},e->{tokenStore.clear();cart.clear();login("Signed out.");});}

    interface Job{JSONObject call()throws Exception;} interface Ok{void ok(JSONObject e)throws Exception;}
    private void run(String label,Job job,Ok ok){if(!label.isEmpty())loading.setVisibility(View.VISIBLE); io.execute(()->{try{JSONObject e=job.call(); main.post(()->{loading.setVisibility(View.GONE); try{ok.ok(e);}catch(Exception x){alert(x.getMessage());}});}catch(Exception x){main.post(()->{loading.setVisibility(View.GONE); error(x);});}});}
    private void error(Exception e){if(e instanceof ApiException){ApiException a=(ApiException)e; if("otp_expired".equals(a.code)){login("Your verification code expired. Please sign in again.");return;} if("register_closed".equals(a.code)){new AlertDialog.Builder(this).setTitle("Register closed").setMessage(a.getMessage()).setPositiveButton("Open register",(d,w)->openRegister(()->{if("checkout".equals(screen))submit("final");else loadMe("Register opened.",true);})).setNegativeButton("Cancel",null).show();return;} alert(a.getMessage());} else alert(e.getMessage()==null?"Network error. Please try again.":e.getMessage());}

    private LinearLayout row(){LinearLayout r=new LinearLayout(this); r.setOrientation(LinearLayout.HORIZONTAL); r.setGravity(Gravity.CENTER_VERTICAL); return r;} private LinearLayout col(){LinearLayout l=new LinearLayout(this); l.setOrientation(LinearLayout.VERTICAL); return l;}
    private void add(View v,int h,int top){content.addView(v,lp(-1,h,top));} private LinearLayout.LayoutParams lp(int w,int h,int top){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(w,h<0?h:dp(h)); p.topMargin=dp(top); return p;}
    private LinearLayout cardBox(){LinearLayout c=col(); c.setPadding(dp(14),dp(12),dp(14),dp(12)); c.setBackground(bg(Color.WHITE,12)); return c;} private void card(String t,String v){LinearLayout c=cardBox(); c.addView(tv(t,12,MUTED,Typeface.BOLD)); c.addView(tv(v,18,INK,Typeface.BOLD)); content.addView(c,lp(-1,-2,8));}
    private void h1(String s){content.addView(tv(s,28,INK,Typeface.BOLD),lp(-1,-2,4));} private void h2(String s){content.addView(tv(s,20,INK,Typeface.BOLD),lp(-1,-2,14));} private void para(String s){TextView t=tv(s,14,MUTED,0); t.setLineSpacing(dp(3),1); content.addView(t,lp(-1,-2,8));}
    private void alert(String s){if(s==null||s.isEmpty())return; TextView t=tv(s,14,BAD,0); t.setPadding(dp(12),dp(10),dp(12),dp(10)); t.setBackground(bg(Color.rgb(255,238,235),10)); content.addView(t,lp(-1,-2,8));}
    private EditText input(String hint,int type){EditText e=new EditText(this); e.setHint(hint); e.setTextSize(15); e.setMinHeight(dp(52)); e.setSingleLine(false); e.setInputType(type); e.setImeOptions(EditorInfo.IME_ACTION_DONE); e.setPadding(dp(12),0,dp(12),0); e.setBackground(bg(Color.WHITE,10)); return e;}
    private Button primary(String s){return btn(s,true);} private Button secondary(String s){return btn(s,false);} private Button tiny(String s){Button b=btn(s,false); b.setTextSize(12); b.setMinWidth(dp(48)); return b;} private Button btn(String s,boolean p){Button b=new Button(this); b.setAllCaps(false); b.setText(s); b.setTypeface(Typeface.DEFAULT,Typeface.BOLD); b.setTextColor(p?Color.WHITE:Color.rgb(221,241,234)); b.setBackground(bg(p?GREEN:DARK2,10)); b.setMinHeight(dp(48)); return b;}
    private TextView tv(String s,int size,int color,int style){TextView t=new TextView(this); t.setText(s); t.setTextSize(size); t.setTextColor(color); t.setTypeface(Typeface.DEFAULT,style); return t;} private GradientDrawable bg(int color,int rad){GradientDrawable g=new GradientDrawable(); g.setColor(color); g.setCornerRadius(dp(rad)); return g;}
    private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);} private double num(EditText e){try{return Double.parseDouble(e.getText().toString());}catch(Exception x){return 0;}} private String cap(String s){return s.substring(0,1).toUpperCase()+s.substring(1);} private String device(){return (Build.MANUFACTURER+" "+Build.MODEL).trim();}
    private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();} private void share(String txt){Intent i=new Intent(Intent.ACTION_SEND); i.setType("text/plain"); i.putExtra(Intent.EXTRA_TEXT,txt); startActivity(Intent.createChooser(i,"Share receipt"));} private void openHttps(String url){if(url==null||!url.startsWith("https://")){toast("Secure invoice link unavailable.");return;} startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(url)));}
    @Override protected void onDestroy(){io.shutdownNow(); super.onDestroy();}
}
